Fix WX_C_BIGENDIAN to work with gcc 14
Before this fix, running configure on Solaris 11.4 x86 with gcc 14
claimed x86 systems were big endian, because the test failed to compile:

conftest.c:38:1: error: return type defaults to 'int' [-Wimplicit-int]
   38 | main () {
      | ^~~~
conftest.c: In function 'main':
conftest.c:46:3: error: implicit declaration of function 'exit' [-Wimplicit-function-declaration]
   46 |   exit (u.c[sizeof (long) - 1] == 1);
      |   ^~~~