Fix SNDCTL_DSP_SPEED configure check on Solaris with gcc 14
Before this fix, running configure on Solaris 11.4 x86 with gcc 14
reported that SNDCTL_DSP_SPEED was not supported because the test
program failed to compile, with the error:

conftest.c: In function 'main':
conftest.c:156:25: error: implicit declaration of function 'ioctl' [-Wimplicit-function-declaration]
  156 |                         ioctl(0, SNDCTL_DSP_SPEED, 0);
      |                         ^~~~~

On Solaris, ioctl() is declared in <unistd.h>