Fix undefined reference to cairo_surface_get_device_scale()
This function needs to be loaded dynamically too.

See #26218.

(cherry picked from commit 583d44d6bc024980f92381c9c11fdaf4db8a20fe)