Fix compilation on OpenIndiana (SunOS)
src/unix/mediactrl.cpp failed to compile due to a precision-losing cast:

mediactrl.cpp: In function 'gint gtk_window_realize_callback(GtkWidget*, wxGStreamerMediaBackend*)':
mediactrl.cpp:310:32: error: cast from 'gpointer' {aka 'void*'} to 'window_id_type' {aka 'unsigned int'} loses precision [-fpermissive]
mediactrl.cpp: In member function 'void wxGStreamerMediaBackend::SetupXOverlay()':
mediactrl.cpp:677:21: error: cast from 'gpointer' {aka 'void*'} to 'window_id_type' {aka 'unsigned int'} loses precision [-fpermissive]

The error can be silenced by casting first to (uintptr_t). Whether this is
the right thing to do is a different matter; the inherent danger of
gpointer's value not fitting in window_id_type remains.

There doesn't appear to be much SunOS-specific about this error, but
it seems that mediactrl.cpp often isn't compiled at all on Linux.