winundef.h is here modified to be compatible with compilations that were not initiated with macro UNICODE assigned.   When this happens, it is full of errors: presumably the wx headers have set _UNICODE so that the windows' xxxW( functions should be directly called, but the declarations calling them do not work.  e.g.:
D:/mingw/msys32/mingw64/include/wx-3.0/wx/msw/winundef.h: In function 'HWND__* CreateWindow(LPCTSTR, LPCTSTR, DWORD, int, int, int, int, HWND, HMENU, HINSTANCE, LPVOID)':
D:/mingw/msys32/mingw64/include/wx-3.0/wx/msw/winundef.h:94:20: error: cannot convert 'LPCTSTR {aka const char*}' to 'LPCWSTR {aka const wchar_t*}' for argument '2' to 'HWND__* CreateWindowExW(DWORD, LPCWSTR, LPCWSTR, DWORD, int, int, int, int, HWND, HMENU, HINSTANCE, LPVOID)'
             return CreateWindowW(lpClassName, lpWndClass, dwStyle, x, y, w, h,
                    ^
In file included from D:/mingw/msys32/mingw64/include/wx-3.0/wx/defs.h:3468:0,
                 from D:/mingw/msys32/mingw64/include/wx-3.0/wx/font.h:18,
                 from F:/plplot-testing/plplot-git/drivers/wxwidgets_comms.h:34,
                 from F:/plplot-testing/plplot-git/drivers/wxwidgets_comms.cpp:20:
D:/mingw/msys32/mingw64/include/wx-3.0/wx/msw/winundef.h: In function 'HMENU__* LoadMenu(HINSTANCE, LPCTSTR)':
D:/mingw/msys32/mingw64/include/wx-3.0/wx/msw/winundef.h:111:44: error: cannot convert 'LPCTSTR {aka const char*}' to 'LPCWSTR {aka const wchar_t*}' for argument '2' to 'HMENU__* LoadMenuW(HINSTANCE, LPCWSTR)'
             return LoadMenuW(instance, name);
                                            ^
The root cause of this discrepancy may lie elsewhere, but this patch seems to make it work.