Fix ANSI build on GCC older than 4.6
Because the wxGCC_ONLY_WARNING_SUPPRESS macro does nothing on GCC <4.6,
the 'format-nonliteral' warning is not suppressed, and compilation would
fail because of the error:
include/wx/wxcrt.h:1057: error: format string argument not a string type

Compilation error detected with GCC 4.4.7 on CentOS 6.