Fix c++11-narrowing error when using clang on Windows
Case value 0xfffffd9f results in the following error:
error: case value evaluates to 4294966687, which cannot be narrowed to type
'DISPID' (aka 'long') [-Wc++11-narrowing]

(cherry picked from commit fd81223a2f878757158b5266c362da71d43abee5)